# Customer Churn Prediction

## Data Understanding & Data Quality Assessment

### Business Problem

Customer churn has a direct impact on revenue and customer acquisition costs.

The objective of this project is to understand customer behavior, identify data quality issues, and prepare a clean dataset for exploratory analysis and machine learning modeling.

### Project Goals

- Understand dataset structure.
- Assess data quality.
- Identify missing values and duplicates.
- Clean and prepare data for analysis.
- Create a reliable foundation for churn prediction.

## Import Libraries

In [57]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

## Load Dataset

In [58]:
df = pd.read_csv('../data/WA_Fn-UseC_-Telco-Customer-Churn.csv')

print('Dataset Loaded Successfully')
df.head()

Dataset Loaded Successfully

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

## Dataset Overview

In [59]:
print(f'Rows: {df.shape[0]}')
print(f'Columns: {df.shape[1]}')

Rows: 7043
Columns: 21

In [60]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.9 MB

In [61]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='str')

## Descriptive Statistics

In [62]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [63]:
df.describe(include='object')

C:\Users\Mohamed\AppData\Local\Temp\ipykernel_20024\4084012645.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include='object')

,customerID,gender,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,TotalCharges,Churn
count,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043
unique,7043,2,2,2,2,3,3,3,3,3,3,3,3,3,2,4,6531,2
top,7590-VHVEG,Male,No,No,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,20.2,No
freq,1,3555,3641,4933,6361,3390,3096,3498,3088,3095,3473,2810,2785,3875,4171,2365,11,5174

## Data Quality Assessment

In [64]:
missing_values = pd.DataFrame(
    df.isnull().sum(),
    columns=['Missing Values']
)

missing_values.sort_values(
    by='Missing Values',
    ascending=False
)

                  Missing Values
customerID                     0
gender                         0
SeniorCitizen                  0
Partner                        0
Dependents                     0
tenure                         0
PhoneService                   0
MultipleLines                  0
InternetService                0
OnlineSecurity                 0
OnlineBackup                   0
DeviceProtection               0
TechSupport                    0
StreamingTV                    0
StreamingMovies                0
Contract                       0
PaperlessBilling               0
PaymentMethod                  0
MonthlyCharges                 0
TotalCharges                   0
Churn                          0

### Hidden Missing Values Check

The TotalCharges column is expected to be numeric. However, in this dataset some records contain blank spaces instead of numeric values.

In [65]:
df[df['TotalCharges'] == ' '].head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,No,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,Yes,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,Yes,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,,No

In [66]:
len(df[df['TotalCharges'] == ' '])

11

## Duplicate Records Check

In [67]:
df.duplicated().sum()

np.int64(0)

## Data Cleaning

In [68]:
df['TotalCharges'] = df['TotalCharges'].replace(' ', np.nan)

df['TotalCharges'] = pd.to_numeric(df['TotalCharges'])

df['TotalCharges'] = df['TotalCharges'].fillna(0)

df['TotalCharges'].dtype

dtype('float64')

In [69]:
df.isnull().sum().sum()

np.int64(0)

## Feature Review

In [70]:
feature_summary = pd.DataFrame({
    'Column': df.columns,
    'Data Type': df.dtypes.values
})

feature_summary

              Column Data Type
0         customerID       str
1             gender       str
2      SeniorCitizen     int64
3            Partner       str
4         Dependents       str
5             tenure     int64
6       PhoneService       str
7      MultipleLines       str
8    InternetService       str
9     OnlineSecurity       str
10      OnlineBackup       str
11  DeviceProtection       str
12       TechSupport       str
13       StreamingTV       str
14   StreamingMovies       str
15          Contract       str
16  PaperlessBilling       str
17     PaymentMethod       str
18    MonthlyCharges   float64
19      TotalCharges   float64
20             Churn       str

## Data Dictionary

| Feature | Description |
|----------|-------------|
| customerID | Unique customer identifier |
| gender | Customer gender |
| SeniorCitizen | Indicates senior citizen status |
| Partner | Customer has partner |
| Dependents | Customer has dependents |
| tenure | Number of months with company |
| PhoneService | Phone service subscription |
| MultipleLines | Multiple phone lines |
| InternetService | Internet service type |
| OnlineSecurity | Online security service |
| OnlineBackup | Online backup service |
| DeviceProtection | Device protection service |
| TechSupport | Technical support subscription |
| StreamingTV | TV streaming service |
| StreamingMovies | Movie streaming service |
| Contract | Contract type |
| PaperlessBilling | Paperless billing |
| PaymentMethod | Payment method |
| MonthlyCharges | Monthly recurring charges |
| TotalCharges | Total accumulated charges |
| Churn | Target variable |

# Summary

### Key Findings

- Dataset contains customer subscription information.
- Dataset includes 7,043 customer records.
- No duplicate records were detected.
- 11 hidden missing values were found in TotalCharges.
- TotalCharges was converted successfully to numeric format.
- Missing values were handled successfully.
- Dataset is now ready for Exploratory Data Analysis (EDA).